export const appConfigLocal = {
  JWT_ACSS_SECRET_LOCAL: '123',
  JWT_REFRESH_SECRET_LOCAL: '123',
  // JWT_ACCESS_EXPIRE_LOCAL: '900s',
  JWT_ACCESS_EXPIRE_LOCAL: '9910s',
  // JWT_REFRESH_EXPIRE_LOCAL: '900s',
  JWT_REFRESH_EXPIRE_LOCAL: '9920s',
};
